def start ():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
def onewrong():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |        O    ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
def twowrong():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |        O    ')
    print ('     |        |    ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
def threewrong():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |        O    ')
    print ('     |       /|    ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
def fourwrong():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |        O    ')
    print ('     |       /|\   ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
def fivewrong():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |        O    ')
    print ('     |       /|\   ')
    print ('     |       /     ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
def dead():
    print ('     _________     ')
    print ('     |/      \|    ')
    print ('     |        |    ')
    print ('     |        O    ')
    print ('     |       /|\   ')
    print ('     |       / \   ')
    print ('     |             ')
    print ('     |             ')
    print ('     |             ')
    print ('-----------        ')
